name: ğŸ‘· Build Installer

on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types: [octoprint_release]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: ğŸ“Œ Checkout
      uses: actions/checkout@v2

    - name: ğŸ‘€ Get OctoPrint Version
      id: octoprint_version
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: OctoPrint/OctoPrint
        excludes: prerelease, draft

    - name: ğŸ”¨ Install OctoPrint into WinPython
      run: |
        WPy64-31040\Scripts\python.bat -m pip install OctoPrint==${{ steps.octoprint_version.outputs.release }}
      shell: cmd

    - name: ğŸ”¨ Build Installer
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" /DOctoPrintVersion="${{ steps.octoprint_version.outputs.release }}" "OctoPrint Setup.iss"
      shell: cmd

    - name: âœï¸ Sign Installer
      uses: dlemstra/code-sign-action@v1
      with:
        certificate: '${{ secrets.CODESIGN }}'
        folder: 'Output'
        recursive: true

    - name: ğŸ§¹ Delete Existing Release and Tag
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: true
        tag_name: ${{ steps.octoprint_version.outputs.release }} # tag name to delete
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: ğŸš€ Create Release and Attach Assets
      uses: softprops/action-gh-release@v1
      with:
        name: "OctoPrint ${{ steps.octoprint_version.outputs.release }} Setup for Windows"
        tag_name: "${{ steps.octoprint_version.outputs.release }}"
        body: "OctoPrint Setup created with Inno Setup using WinPython, winsw, and GitHub Actions."
        fail_on_unmatched_files: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          Output\OctoPrint Setup ${{ steps.octoprint_version.outputs.release }}.exe
